### ISSUE TITLE
bro please

### ISSUE THREAD

**Issue by nicolaeser** [NICK-FURY-6023/LyricLoom#69]
bro stop pushing your auth secrets, tokens and database logins to github and use an env file please

**Comment by nicolaeser** [comment]
[![https___s3 us-east-1 amazonaws com_pocket-collectionapi-prod-images_bd424d31-3d7c-4acf-b283-ba46153e6c3e](https://github.com/user-attachments/assets/958d6c98-e7bb-4bd1-8157-64b88852b4a5)
](https://pocket-image-cache.com/648x/filters:format(png):extract_focal()/https%3A%2F%2Fs3.us-east-1.amazonaws.com%2Fpocket-collectionapi-prod-images%2Fbd424d31-3d7c-4acf-b283-ba46153e6c3e.jpeg)

**Comment by nicolaeser** [comment]
https://c.tenor.com/meWz42NgsPkAAAAd/tenor.gif

**Comment by nicolaeser** [comment]
How Life feels without publishing sensible and important login data to the github page

![GIF](https://c.tenor.com/meWz42NgsPkAAAAd/tenor.gif)

**Comment by nicolaeser** [comment]
![ezgif-1-ba441cbe3d](https://github.com/user-attachments/assets/282cb58f-8284-430b-85d3-ae5cd2cb177c)

**Comment by nicolaeser** [comment]
How Life feels without publishing sensible and important login data to the github page

![ezgif-1-ba441cbe3d](https://github.com/user-attachments/assets/a18e4c2f-42a6-41da-a9a0-19aa4665893f)

**Comment by NICK-FURY-6023** [comment]
yes you are right  but if you want  my toekn & database then you can use if it's works lol_xd

 i know what i do
